version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: procurepilot-postgres
    environment:
      POSTGRES_DB: procurepilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../infrastructure/Dockerfile.backend
    container_name: procurepilot-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: procurepilot
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      AI_SERVICE_URL: http://ai-service:8000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build:
      context: ./ai-service
      dockerfile: ../infrastructure/Dockerfile.aiservice
    container_name: procurepilot-ai-service
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    container_name: procurepilot-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
